### ISSUE TITLE
对于小白如何部署

### ISSUE THREAD

**Issue by jiangbeth** [daibor/bus-route-radiation-map#1]
感谢大佬的辛苦付出，能不能出一个一键搭建的脚本，谢谢了

**Comment by daibor** [comment]
@jiangbeth 可以先用 [https://busline-map.vercel.app/busline](https://busline-map.vercel.app/busline) ，注册高德地图开发者，配置一下 key 就行。代码目前还没达到开源状态，完善后推到本仓库，另外也会支持使用 [vercel](https://vercel.com/) 一键部署。
