### ISSUE TITLE
请问不能使用了吗

### ISSUE THREAD

**Issue by JoesenPro** [daibor/bus-route-radiation-map#6]
如题

**Comment by daibor** [comment]
原来的方式无法使用了，需要参考 readme 前往基于开源代码搭建的网站 https://busline-map.vercel.app/busline，并按照提示完成配置后使用

**Comment by JoesenPro** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
